[package]
name = "telegram_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.52"
quote = "1.0.35"

[dependencies.telegram_bots_api]
path = "../telegram_bots_api"
features = []
